import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ZekoAiNavBar from "@/components/ui/navbar";
import { ScrollArea , ScrollBar} from "@/components/ui/scroll-area"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ScrollArea className="h-screen">
        <ZekoAiNavBar/>
        {children}
        <ScrollBar/>
        </ScrollArea>
      </body>
    </html>
  );
}
